import type {Metadata} from "next";
import "./globals.css";
import {Montserrat} from "next/font/google";
import {ReactNode} from "react";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Israelcart",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
}

export default function RootLayout(
  {
    children,
  }: Props) {

  return (
    <html lang="en">
    <meta name={"robots"} content={"noindex"}/>
    <body className={`${montserrat.className}`}>
    {children}
    </body>
    </html>
  );
}
